### ISSUE TITLE
No Domain configuration shown within the DNS settings of root page

### ISSUE THREAD

**Issue by oliverkieslich** [richardhj/contao-multidns#1]
I have installed the module on contao 3.5.12 and no error appears during installation. When I open settings of the root page, the input field for the domain within DSN settings is gone. Only this appears: 
![shot](https://cloud.githubusercontent.com/assets/13046663/15217717/1a8447bc-185d-11e6-92eb-9ba547845d39.jpg)

Is this a bug? Or how can I configure the multiple DNS settings for the root page? 

Thank you and kind regards

Oliver

**Comment by richardhj** [comment]
I missed adding the MultiColumnWizard to the dependencies. Please update (You're using composer?) and give review. Thanks for the advice!

**Comment by oliverkieslich** [comment]
Thank you for your support.

I´ve updated the module but without any effect. The domain input field still doesn't appear. 
I don't use composer, I just download the ZIP file and install the module manually. Afterwards I clear the cache.

**Comment by richardhj** [comment]
Ok, in that case you have to install MultiColumnWizard at your own/manually or over the extension repository. These are the things, composer would do for you too ;)

**Comment by oliverkieslich** [comment]
Ahh here we go. It works like a charme. Thank you !
